@host = http://localhost:9999

### test api
POST {{host}}/api
Content-Type: application/json

{
    "method": "socket.clients",
    "appkey": "abc",
    "timestamp": 123,
    "v":"1.0",
    "param":{},
    "sign":"abc"
}